public with sharing class adminBeginer {
    public adminBeginer() {

        /* 
        1-get started with apex 
            -- write comments 2ways
            -- write pseudocode = write a suite f instruction on what the program need to do 
        2-practice in the developer console 
            -- varibales tpes : Integer , Decim , String , Boolean , ID(salesforce record ID = 18caract) 
            -- System.Debug() -> execute anonymous + open log for info
            -- all the types we mentionned have a null values as default
            -- we have : 
                declaration 
                assigning value
        3-use collections
            -- list       
                declare empty list 
                declare a list with defined size 
                initialize a list
                method to add to list 
                    add() => add at the end 
                    add(index,value) => add at the index and push the old value to next case
                get size 
                access values with index
            !demystifiying lists
                if a mist id declared with a size but not values iitialization 
                , the add() add all your values after the size = end of list so it
                might be like null,null,milk
        4-control data flow
            -- if
            -- if else block 
            -- if else if else blocks
            -- switch statement 
                --- switch variable
                    when 'vales 1','value 2'
                    when 'value 3'
                    default
            -- logical operator && ||
            -- mathematical operator 
        5-use loops
        -- for loop
        -- while loop
        -- do while loop
            break -->break the while loop 
            continue --> continue to the next iteration of the loop
        */
    }
}